fix display_via_github in manifest for several winning entries
Performed even more bin tool edits needed to get ready for the **IOCCC29**
`2025` winners.

Improved the help message for `bin/all-run.sh`.
Improved the help message for `bin/all-years.sh`.

Fixed how the `bin/cvt-submission.sh` tool sets in the `.entry.json`
files, the `display_via_github` value (determines if the inventory item
references the file in GitHub: if `"display_via_github" : true`, or is
attempted to be displayed in the browser / downloaded by the browser if if
`"display_via_github" : false`).

The `bin/cvt-submission.sh` tool can use various `display_as` values in the
manifest of the `.entry.json` file to force the "display_via_github"`
boolean.

The following `display_as` values will force `"display_via_github" : false`,
and thus cause the browser to either display the file content directory,
or cause the browser to download the file content (unless the file is
a dot-file):

- binary
- bz2
- bzip2
- gzip
- html
- image
- kernel
- midi
- mp3
- pdf
- rgb
- spreadsheet
- tarball
- tbz2
- wav
- zip

Add `make verify_display_as` to top level `Makefile` to run `bin/bad-display-as.sh`
for all `.entry.json` files to verify the above bullet list.

The `bin/cvt-submission.sh` tool, if the `"file_path"` starts with a "**.**"
(if a dot-file), then `"display_via_github" : true` is set.

All other `display_as` values, and all dot-files will force:
`"display_via_github" : true`.

Changed `VERSION` of `bin/cvt-submission.sh` to "2.3.4 2026-04-28".

Add `bin/bad-display-as.sh` to test for invalid `display_as` /
`display_via_github` combos in `.entry.json` files.

Updated `bin/README.md` as per the above.

Changed `"display_via_github"` to `true for `.path` files all 2024 winning entries.

Fixed a number of `display_as` / `display_via_github` combos for `2000/schneiderwent`.
Fixed a number of `display_as` / `display_via_github` combos for `2005/sykes`.
Fixed a number of `display_as` / `display_via_github` combos for `2012/grothe`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/burton`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/carlini`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/carlini`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/macke`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/mills`.
Fixed a number of `display_as` / `display_via_github` combos for `2024/weaver`.

Added `make submit_line` to year level `YYYY/Makefile`s to echo the list of
winning entries on a single line.

Added `make submit_list` to year level `YYYY/Makefile`s to the list of
winning entries, one per line.

Regularized `make new_entry` in year level `YYYY/Makefile`s.

Improved `make test` help description in top level `Makefile`.

Added `bin/update-entry.sh` to update a newly created winning entry
that has just been converted from submission form by `bin/cvt-submission.sh`.

Updated the web pages, tarballs, and sitemap as per the above.

diff --git a/1993/Makefile b/1993/Makefile
--- a/1993/Makefile
+++ b/1993/Makefile
@@ -261,12 +261,41 @@ genpath:
 # NOTE: 'Don't Panic' if you don't understand the stuff below
 #############################################################
 
-# add ${NEW_ENTRY} to the list of ${ENTRIES} and output Makefile lines to set updated ${ENTRIES} value
+# new_entry - add a new entry directory name to the ${ENTRIES} Makefile variable
+#
+# Add ${NEW_ENTRY} to the list of ${ENTRIES} and output Makefile lines to set updated
+# ${ENTRIES} Makefile variable.
+#
+# If list of ${ENTRIES} is long, we format it into a multi-line value setting with required
+# backslashes and indentation.  Duplicate values are removed and the initial 'submit.[0-9]*' (used
+# during judging) is removed.  The words (directory names) in ${ENTRIES} are sorted in C dictionary order.
+#
+# This rule is used by the bin/new-dir.sh shell script via:
+#
+#	make -C ${YEAR} new_entry NEW_ENTRY=curds
 #
 new_entry:
-	@(echo 'ENTRIES= '; \
-	  (echo ${ENTRIES} ${NEW_ENTRY}) | ${TR} ' ' '\012' | ${SORT} -d -u) | \
-	  ${FMT} | ${SED} -e '2,$$s/^/\t/' -e 's/$$/ \\/' -e '$$s/ \\//'
+	@if [[ -z "${NEW_ENTRY}" ]]; then echo "$@: ERROR: NEW_ENTRY is empty" 1>&2; exit 1; fi
+	@if [[ ! -d "${NEW_ENTRY}" ]]; then echo "$@: ERROR: not a directory: ${YEAR}/${NEW_ENTRY}" 1>&2; exit 2; fi
+	@(echo -n 'ENTRIES= '; \
+	   (for dir in ${ENTRIES} ${NEW_ENTRY}; do \
+	      if [[ $$dir != 'submit.[0-9]*' ]]; then echo "$$dir"; fi; \
+	    done | \
+	    LANG=C ${SORT} -d -u; \
+	   ) \
+	 ) | \
+	 ${FMT} | \
+	 ${SED} -e '2,$$s/^/\t/' -e 's/$$/ \\/' -e '$$s/ \\//'
+
+# submit_line - echo the list of winning entries on a single line
+#
+submit_line:
+	@echo ${ENTRIES}
+
+# submit_list - echo the list of winning entries, one per line
+#
+submit_list:
+	@for i in ${ENTRIES}; do echo "$$i" ; done
 
 
 ########################
